name: django_venv
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
# - libcxx
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - asgiref==3.5.0
    - django==4.0.1
    - numpy==1.22.2
    - pandas==1.4.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - six==1.16.0
    - sqlparse==0.4.2
    - pyyaml
    - authlib
